In [2]:
import numpy as np
import multiprocessing as mp
import random
import re
import sys
import scipy.sparse

In [3]:
def softprojc(vec, i, c = -1e-5):
    return(np.where(vec < c, c, vec))
def softproji(vec, i):
    return(np.where(vec < 0, (-1 / np.sqrt(i)), vec))

In [4]:
# mode 1 samples rows
def weightsample(data, mode):
    prob = np.linalg.norm(data, axis=mode)
    return(prob / sum(prob))

In [5]:
def als(data, k, niter, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    for j in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])

        for i in np.arange(niter):            
            # sample random row or column
            row = np.random.randint(data.shape[0])
            col = np.random.randint(data.shape[1])
            
            # perform linear reg update 
            rfactor[:, col] = np.matmul(np.linalg.pinv(lfactor), data[:, col])
            lfactor[row, :] = np.matmul(data[row, :], np.matmul(rfactor.T, np.linalg.inv(np.matmul(rfactor, rfactor.T))))
            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[niter - 1]):
            finalerror = seqerror[niter - 1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    return(lbest, rbest, lowesterror)

In [6]:
def rk(data, k, niter, kacziter, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    for l in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])
        
        # outer loop for number of iterations 
        for i in np.arange(niter):
            approx = np.matmul(lfactor, rfactor)
            
            # weighted sampling of row and column from data approx matrix
            row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
            col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))
            
            # inner loop for number of RK iterations
            for j in np.arange(kacziter):
                # sample index for entry of data matrix
                kaczrow = np.random.choice(lfactor.shape[0], size = 1, p = weightsample(lfactor, 1))
                kaczcol = np.random.choice(rfactor.shape[1], size = 1, p = weightsample(rfactor, 0))

                # compute RK step
                lfactor[row, :] = lfactor[row, :] + (data[row, kaczcol] - np.matmul(lfactor[row, :], rfactor[:, kaczcol])) / (np.linalg.norm(rfactor[:, kaczcol])**2) * rfactor[:, kaczcol].T 
                rfactor[:, col] = rfactor[:, col] + (data[kaczrow, col] - np.matmul(lfactor[kaczrow, :], rfactor[:, col])) / (np.linalg.norm(lfactor[kaczrow, :])**2) * lfactor[kaczrow, :].T
     
            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[niter - 1]):
            finalerror = seqerror[niter - 1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    return(lbest, rbest, lowesterror)

In [7]:
def brk(data, k, s, niter, kacziter, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    for l in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])
        
        # outer loop for number of iterations 
        for i in np.arange(niter):
            approx = np.matmul(lfactor, rfactor)
            
            # weighted sampling of row and column from data matrix
            row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
            col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))
            #row = np.random.choice(data.shape[0], p = weightsample(approx, 1))
            #col = np.random.choice(data.shape[1], p = weightsample(approx, 0))
            
            # inner loop for number of RK iterations
            for j in np.arange(kacziter):
                # sample indices until at least one nonzero row or col
                
                resample = True
                while(resample):
                    rowsum = 0
                    colsum = 0
                    kaczrow = np.random.choice(lfactor.shape[0], size = s, replace = False)
                    kaczcol = np.random.choice(rfactor.shape[1], size = s, replace = False)

                    for samplerow in kaczrow:
                        rowsum = rowsum + sum(lfactor[samplerow, :])
                    for samplecol in kaczcol:
                        colsum = colsum + sum(rfactor[:, samplerow])
                    if (rowsum > 0 and colsum > 0):
                        resample = False

                # compute BRK step
                #kaczrow = np.random.choice(lfactor.shape[0], size = s, replace = False)
                #kaczcol = np.random.choice(rfactor.shape[1], size = s, replace = False)

                lfactor[row, :] = lfactor[row, :] + np.matmul((data[row, kaczcol] - np.matmul(lfactor[row, :], rfactor[:, kaczcol])), np.linalg.pinv(rfactor[:, kaczcol]))
                rfactor[:, col] = rfactor[:, col] + np.matmul(np.linalg.pinv(lfactor[kaczrow, :]), (data[kaczrow, col, None] - np.matmul(lfactor[kaczrow, :], rfactor[:, col])))

            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[niter - 1]):
            finalerror = seqerror[niter - 1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    return(lbest, rbest, lowesterror)

In [8]:
def gs(data, k, niter, gsiter, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    for l in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])
        
        # outer loop for number of iterations 
        for i in np.arange(niter):
            approx = np.matmul(lfactor, rfactor)
            
            # weighted sampling of row and column from data matrix
            #row = np.random.choice(data.shape[0], p = weightsample(approx, 1))
            #col = np.random.choice(data.shape[1], p = weightsample(approx, 0))
            row = np.random.choice(data.shape[0])
            col = np.random.choice(data.shape[1])
            
            # inner loop for number of RK iterations
            for j in np.arange(gsiter):
                # sample indices for entry of data matrix, dont want norms in rk step to be 0
                #gsrow = np.random.choice(rfactor.shape[0], replace = False, p = weightsample(rfactor, 1))
                #gscol = np.random.choice(lfactor.shape[1], replace = False, p = weightsample(lfactor, 0))
                gsrow = np.random.choice(rfactor.shape[0])
                gscol = np.random.choice(lfactor.shape[1])
            
                # compute GS step
                rfactor[:, col] = rfactor[:, col] + np.matmul(lfactor[:, gscol].T, (data[:, col] - np.matmul(lfactor, rfactor[:, col])), np.eye(k)[:, gscol])
                lfactor[row, :] = lfactor[row, :] + np.matmul((data[row, :] - np.matmul(lfactor[row, :], rfactor)), np.matmul(np.array([rfactor[gsrow, :]]).T, np.array([np.eye(k)[gsrow, :]])))
                
            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[niter - 1]):
            finalerror = seqerror[niter - 1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    return(lbest, rbest, lowesterror)

In [9]:
def bgs(data, k, s, niter, gsiter, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    for l in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])
        
        # outer loop for number of iterations 
        for i in np.arange(niter):
            approx = np.matmul(lfactor, rfactor)
            
            # weighted sampling of row and column from data matrix
            #row = np.random.choice(data.shape[0], p = weightsample(approx, 1))
            #col = np.random.choice(data.shape[1], p = weightsample(approx, 0))
            row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
            col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))
            
            
            # inner loop for number of RK iterations
            for j in np.arange(gsiter):
                # sample indices for entry of data matrix, dont want norms in rk step to be 0
                #gsrow = np.random.choice(rfactor.shape[0], size = s, replace = False, p = weightsample(rfactor, 1))
                #gscol = np.random.choice(lfactor.shape[1], size = s, replace = False, p = weightsample(lfactor, 0))
                
                if s == 1:
                    gsrow = np.random.choice(rfactor.shape[0], size = s, p = weightsample(rfactor, 1))
                    gscol = np.random.choice(lfactor.shape[1], size = s, p = weightsample(lfactor, 0))

                else:
                    resample = True
                    while(resample):
                        rowsum = 0
                        colsum = 0
                        gscol = np.random.choice(lfactor.shape[1], size = s, replace = False)
                        gsrow = np.random.choice(rfactor.shape[0], size = s, replace = False)

                        for samplerow in gsrow:
                            rowsum = rowsum + sum(lfactor[samplerow, :])
                        for samplecol in gscol:
                            colsum = colsum + sum(rfactor[:, samplerow])
                        if (rowsum > 0 and colsum > 0):
                            resample = False

                # compute BGS step
                lfactor[row, :] = lfactor[row, :] + np.matmul((data[row, :] - np.matmul(lfactor[row, :], rfactor)), np.matmul(np.linalg.pinv(rfactor[gsrow, :]), np.eye(k)[:, gscol].T))
                rfactor[:, col] = rfactor[:, col] + np.matmul(np.matmul(np.eye(k)[:, gscol], np.linalg.pinv(lfactor[:, gscol])), (data[:, col] - np.matmul(lfactor, rfactor[:, col])))
        
            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[niter - 1]):
            finalerror = seqerror[niter - 1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    return(lbest, rbest, lowesterror)

In [10]:
def alstest(data, k, niter, reinit = 1):
    A, S, e = als(data, k = k, niter = niter, reinit = reinit)
    approx = np.matmul(A, S)
    return((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [11]:
def rktest(data, k, niter, kacziter, reinit = 1):
    A, S, error = rk(data, k = k, niter = niter, kacziter = kacziter, reinit = reinit)
    approx = np.matmul(A, S)
    return((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [12]:
def brktest(data, k, s, niter, kacziter, reinit = 1):
    A, S, error = brk(data, k = k, s = s,  niter = niter, kacziter = kacziter, reinit = reinit)
    approx = np.matmul(A, S)
    return((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [13]:
def listener(q, textfile):
    '''listens for messages on the q, writes to file. '''
    with open(textfile, 'w') as f:
        while 1:
            m = q.get()
            if m == 'kill':
                f.write('killed')
                break
            f.write(str(m) + ', ')
            f.flush()

In [14]:
def read(filename): 
    with open(filename, 'r') as f:
        l = f.read().split(',')
    return(l)

In [15]:
def alswrite(data, k, niter, q):
    A, S, e = als(data, k = k, niter = niter)
    approx = np.matmul(A, S)
    q.put((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [16]:
def rkwrite(data, k, niter, kacziter, q):
    A, S, error = rk(data, k = k, niter = niter, kacziter = kacziter)
    approx = np.matmul(A, S)
    q.put((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [17]:
def brkwrite(data, k, s, niter, kacziter, q):
    A, S, error = brk(data, k = k, s = s, niter = niter, kacziter = kacziter)
    approx = np.matmul(A, S)
    q.put((np.linalg.norm(data - approx) / np.linalg.norm(data)))

In [18]:
def alsmp(data, k, niter, filename, loop, cores = mp.cpu_count()):
    manager = mp.Manager()
    q = manager.Queue()    
    pool = mp.Pool(cores)

    #put listener to work first
    watcher = pool.apply_async(listener, (q, filename))

    #fire off workers
    jobs = []
    for i in range(loop):
        job = pool.apply_async(alswrite, (data, 4, 100, q))
        jobs.append(job)

    # collect results from the workers through the pool result queue
    for job in jobs: 
        job.get()

    #now we are done, kill the listener
    q.put('kill')
    pool.close()
    pool.join()

In [19]:
def rkmp(data, k, niter, kacziter, filename, loop, cores = mp.cpu_count()): 
    manager = mp.Manager()
    q = manager.Queue()    
    pool = mp.Pool(cores)

    #put listener to work first
    watcher = pool.apply_async(listener, (q, filename))

    #fire off workers
    jobs = []
    for i in range(loop):
        job = pool.apply_async(rkwrite, (data, k, niter, kacziter, q))
        jobs.append(job)

    # collect results from the workers through the pool result queue
    for job in jobs: 
        job.get()

    #now we are done, kill the listener
    q.put('kill')
    pool.close()
    pool.join()

In [20]:
def brkmp(data, k, s, niter, kacziter, filename, loop, cores = mp.cpu_count()): 
    manager = mp.Manager()
    q = manager.Queue()    
    pool = mp.Pool(cores)

    #put listener to work first
    watcher = pool.apply_async(listener, (q, filename))

    #fire off workers
    jobs = []
    for i in range(loop):
        job = pool.apply_async(brkwrite, (data, k, s, niter, kacziter, q))
        jobs.append(job)

    # collect results from the workers through the pool result queue
    for job in jobs: 
        job.get()

    #now we are done, kill the listener
    q.put('kill')
    pool.close()
    pool.join()

In [21]:
def extracterr(tag, errfiles): 
    r = re.compile(".*(" + tag + ").*")
    files = list(filter(r.match, errfiles))
    title = list()
    meanerr = list()
    stderr = list()
    for f in reversed(files):
        title.append("".join(re.findall('[0-9]+k*', f)[0]))
        meanerr.append(np.mean(np.asarray(read(f)[:-1]).astype(float)))
        stderr.append(np.std(np.asarray(read(f)[:-1]).astype(float)))
    return(title, meanerr, stderr)

In [22]:
def alsupdate(data, lf, rf, s, siter):
    row = np.random.randint(data.shape[0], size = 1)
    col = np.random.randint(data.shape[1], size = 1)
            
    # perform linear reg update 
    for i in np.arange(siter):
        rf[:, col] = np.matmul(np.linalg.pinv(lf), data[:, col])
        lf[row, :] = np.matmul(data[row, :], np.matmul(rf.T, np.linalg.inv(np.matmul(rf, rf.T))))
    return(lf, rf)

In [23]:
def brkupdate(data, lf, rf, s, siter):
    approx = np.matmul(lf, rf)
            
    # weighted sampling of row and column from data matrix
    # specifying size returns an array rather than a scalar
    row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
    col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))

    # inner loop for number of BRK iterations
    for j in np.arange(siter):
        if s == 1:
            # sample index for entry of data matrix
            kaczrow = np.random.choice(lf.shape[0], size = s, p = weightsample(lf, 1))
            kaczcol = np.random.choice(rf.shape[1], size = s, p = weightsample(rf, 0))
        else:
            resample = True
            while(resample):
                rowsum = 0
                colsum = 0
                kaczrow = np.random.choice(lf.shape[0], size = s, replace = False)
                kaczcol = np.random.choice(rf.shape[1], size = s, replace = False)

                for samplerow in kaczrow:
                    rowsum = rowsum + sum(lf[samplerow, :])
                for samplecol in kaczcol:
                    colsum = colsum + sum(rf[:, samplerow])
                if (rowsum > 0 and colsum > 0):
                    resample = False

            # compute BRK step
    
        lf[row, :] = lf[row, :] + np.matmul((data[None, row, kaczcol] - np.matmul(lf[row, :], rf[:, kaczcol])), np.linalg.pinv(rf[:, kaczcol]))
        rf[:, col] = rf[:, col] + np.matmul(np.linalg.pinv(lf[kaczrow, :]), (data[kaczrow, col, None] - np.matmul(lf[kaczrow, :], rf[:, col])))

    return(lf, rf)

In [62]:
def bgsupdate(data, lf, rf, s, siter):
    approx = np.matmul(lf, rf)
    k = lf.shape[1]
            
    # weighted sampling of row and column from data matrix
    # specifying size returns an array rather than a scalar
    row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
    col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))

    # inner loop for number of GS iterations
    for j in np.arange(siter):
        if s == 1:
            gsrow = np.random.choice(rf.shape[0], size = s, p = weightsample(rf, 1))
            gscol = np.random.choice(lf.shape[1], size = s, p = weightsample(lf, 0))
        else:
            resample = True
            while(resample):
                rowsum = 0
                colsum = 0
                gscol = np.random.choice(lf.shape[1], size = s, replace = False)
                gsrow = np.random.choice(rf.shape[0], size = s, replace = False)

                for samplerow in gsrow:
                    rowsum = rowsum + sum(lf[samplerow, :])
                for samplecol in gscol:
                    colsum = colsum + sum(rf[:, samplerow])
                if (rowsum > 0 and colsum > 0):
                    resample = False

        # compute BGS step
        print(np.matmul((data[row, :] - np.matmul(lf[row, :], rf)), np.matmul(np.linalg.pinv(rf[gsrow, :]), np.eye(k)[:, gscol].T)))
        print(np.matmul(np.matmul(np.eye(k)[:, gscol], np.linalg.pinv(lf[:, gscol])), (data[:, col] - np.matmul(lf, rf[:, col]))))
        lf[row, :] = lf[row, :] + np.matmul((data[row, :] - np.matmul(lf[row, :], rf)), np.matmul(np.linalg.pinv(rf[gsrow, :]), np.eye(k)[:, gscol].T))
        rf[:, col] = rf[:, col] + np.matmul(np.matmul(np.eye(k)[:, gscol], np.linalg.pinv(lf[:, gscol])), (data[:, col] - np.matmul(lf, rf[:, col])))
        #print(np.linalg.norm(np.eye(data.shape[0]) - np.matmul(np.linalg.pinv(np.matmul(lf, rf)), np.matmul(lf, rf))))

    return(lf, rf)

In [57]:
def mf(data, k, s = 1, niter = 100, siter = 1, solver = 'als', errseq = False, reinit = 1):
    # set to negative one so we can guarantee an update for the first init
    finalerror = -1
    rows = np.empty(niter)
    
    # need to compare final error to overall best and store the overall best
    seqerror = np.empty(niter)
    lowesterror = np.empty(1)
    
    # store overall best factor matrices
    lbest = np.random.rand(data.shape[0], k)
    rbest = np.random.rand(k, data.shape[1])
    
    # for bgs, siter > 1 throws an error 
    if solver == "als":
        f = alsupdate
    if solver == "brk":
        f = brkupdate
    if solver == "bgs":
        f = bgsupdate
    
    for l in np.arange(reinit):
        # randomly initialize the factor matrices
        lfactor = np.random.rand(data.shape[0], k)
        rfactor = np.random.rand(k, data.shape[1])
        
        # outer loop for number of iterations 
        for i in np.arange(niter):          
            lfactor, rfactor = f(data, lfactor, rfactor, s, siter)
            
            # calculate error after update
            seqerror[i] = np.linalg.norm(data - np.matmul(lfactor, rfactor)) / np.linalg.norm(data)
        # update after first init
        if (finalerror == -1):
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
        # if not first, only update if final error is lower than overall best
        elif (finalerror > seqerror[-1]):
            finalerror = seqerror[-1]
            lowesterror = seqerror
            lbest = lfactor
            rbest = rfactor
    if (errseq):
        return(lbest, rbest, lowesterror)
    else:
        return(lbest, rbest, lowesterror[-1])

In [26]:
def mfwrite(data, k, s, niter, siter, solver, q, errseq = False, reinit = 1):
    A, S, error = mf(data, k, s, niter, siter, solver, errseq, reinit)
    q.put(error)

In [27]:
def mpmf(data, k, s, niter, siter, solver, filename, loop, cores = mp.cpu_count()):
    manager = mp.Manager()
    q = manager.Queue()    
    pool = mp.Pool(cores)

    #put listener to work first
    watcher = pool.apply_async(listener, (q, filename))

    #fire off workers
    jobs = []
    for i in range(loop):
        job = pool.apply_async(mfwrite, (data, k, s, niter, siter, solver, q))
        jobs.append(job)

    # collect results from the workers through the pool result queue
    for job in jobs: 
        job.get()

    #now we are done, kill the listener
    q.put('kill')
    pool.close()
    pool.join()

In [60]:
sfactor200 = np.random.choice(4, size=(200,4), p=np.array([0.7, 0.1, 0.1, 0.1]))
sweight200 = np.random.randint(0, 2, size=(4, 200))
data = np.matmul(sfactor200, sweight200)

In [63]:
A, S, error = mf(data, k = 4, s = 1, niter = 10, siter = 1000, solver = 'bgs')

[[0.         0.         0.         0.39183316]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.99936645]]
[[0.         0.         0.         0.04664296]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.38777878e-16]]
[[0.00624724 0.         0.         0.        ]]
[[0.26239276]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.13340814 0.         0.         0.        ]]
[[-8.32667268e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.10039727  0.          0.          0.        ]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[-1.66851477e-05  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[4.16333634e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.          0.         -0.20524735]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.19928204]]
[[0.         0.         0.         0.15429454]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.66533454e-16]]
[[0.         0.         0.         0.15518642]]
[[0.00000000e+00]
 [0.00000000e+00]


[[0.         0.         0.12360376 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.01531242]
 [ 0.        ]]
[[ 0.          0.          0.         -0.22589555]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00654394]]
[[-0.00010303  0.          0.          0.        ]]
[[-0.01026852]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.21155884 0.        ]]
[[0.        ]
 [0.        ]
 [0.02524851]
 [0.        ]]
[[ 0.         -0.15903758  0.          0.        ]]
[[0.        ]
 [0.00770491]
 [0.        ]
 [0.        ]]
[[-0.17226268  0.          0.          0.        ]]
[[-0.02741121]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.07491661 0.         0.        ]]
[[0.        ]
 [0.02824463]
 [0.        ]
 [0.        ]]
[[-0.11242448  0.          0.          0.        ]]
[[-0.02177567]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.10212089 0.         0.         0.        ]]
[[1.38777878e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]

[[0.        0.        0.        0.1850449]]
[[0.       ]
 [0.       ]
 [0.       ]
 [0.0014176]]
[[0.40652871 0.         0.         0.        ]]
[[0.00466506]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -0.49731997  0.          0.        ]]
[[ 0.        ]
 [-0.00582168]
 [ 0.        ]
 [ 0.        ]]
[[-0.00072057  0.          0.          0.        ]]
[[-0.00771989]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-0.10806944  0.          0.          0.        ]]
[[6.24500451e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.03029912  0.          0.          0.        ]]
[[3.46944695e-18]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.57053274 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.01543738]
 [ 0.        ]]
[[ 0.          0.         -0.43512394  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.72458747e-17]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         -0.10989661]]
[[0.       ]
 [0.       ]
 [0.  

 [-5.55111512e-17]]
[[ 0.         -0.54460456  0.          0.        ]]
[[0.        ]
 [0.00526365]
 [0.        ]
 [0.        ]]
[[0.38798189 0.         0.         0.        ]]
[[-0.03327986]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.09593803 0.         0.        ]]
[[0.        ]
 [0.01162539]
 [0.        ]
 [0.        ]]
[[0.04148941 0.         0.         0.        ]]
[[-0.00681631]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.04188726]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00444719]]
[[0.         0.03044717 0.         0.        ]]
[[0.        ]
 [0.00265494]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         0.00851453]]
[[ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [-0.0011585]]
[[ 0.          0.          0.         -0.43635575]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]]
[[0.         0.35399684 0.         0.        ]]
[[0.        ]
 [0.02155802]
 [0.        ]
 [0.      

[[0.00227239]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.00000000e+00 3.89511565e-06 0.00000000e+00 0.00000000e+00]]
[[0.        ]
 [0.00051727]
 [0.        ]
 [0.        ]]
[[-0.13382112  0.          0.          0.        ]]
[[-0.0004239]
 [ 0.       ]
 [ 0.       ]
 [ 0.       ]]
[[-0.19547037  0.          0.          0.        ]]
[[-9.71445147e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.23966324 0.        ]]
[[0.        ]
 [0.        ]
 [0.00136536]
 [0.        ]]
[[ 0.          0.          0.         -0.23890448]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00117347]]
[[ 0.        -0.0319934  0.         0.       ]]
[[0.        ]
 [0.01123838]
 [0.        ]
 [0.        ]]
[[0.2159155 0.        0.        0.       ]]
[[-0.01462917]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.05876481]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00022048]]
[[0.         0.         0.04556043 0.        ]]
[[ 

[[ 0.        ]
 [ 0.        ]
 [-0.00053072]
 [ 0.        ]]
[[0.        0.        0.        0.1776898]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00117849]]
[[0.         0.00467272 0.         0.        ]]
[[ 0.        ]
 [-0.00517064]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.00151212 0.         0.        ]]
[[ 0.00000000e+00]
 [-1.87350135e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00045509 0.         0.         0.        ]]
[[0.00599679]
 [0.        ]
 [0.        ]
 [0.        ]]
[[-0.19560962  0.          0.          0.        ]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.02816823 0.         0.         0.        ]]
[[2.01227923e-16]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.15132336 0.         0.        ]]
[[ 0.        ]
 [-0.00168219]
 [ 0.        ]
 [ 0.        ]]
[[0.        0.0423655 0.        0.       ]]
[[0.00000000e+00]
 [7.63278329e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         -0.12722624  0.          0.        ]]
[[0.00000000e+00]
 [1.4

 [ 0.        ]]
[[-0.03840375  0.          0.          0.        ]]
[[0.00233621]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -0.01082721  0.          0.        ]]
[[ 0.        ]
 [-0.00106934]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.03809698]]
[[0.       ]
 [0.       ]
 [0.       ]
 [0.0012165]]
[[0.00733444 0.         0.         0.        ]]
[[-9.72171648e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.04660983  0.          0.          0.        ]]
[[6.24500451e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -0.21623442  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00372878]
 [ 0.        ]]
[[0.         0.14752694 0.         0.        ]]
[[0.        ]
 [0.00197521]
 [0.        ]
 [0.        ]]
[[0.         0.         0.04451923 0.        ]]
[[0.        ]
 [0.        ]
 [0.00010643]
 [0.        ]]
[[0.01145604 0.         0.         0.        ]]
[[0.00420161]
 [0.        ]
 [0.        

[[ 0.          0.         -0.12396285  0.        ]]
[[0.        ]
 [0.        ]
 [0.03013359]
 [0.        ]]
[[0.41908992 0.         0.         0.        ]]
[[0.02283096]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -0.00133023]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.14631778]]
[[0.00109953 0.         0.         0.        ]]
[[-0.10213973]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.22908538  0.          0.        ]]
[[ 0.        ]
 [-0.06761428]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.27765326]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.12102923]]
[[ 0.          0.         -0.00025761  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.08981092]
 [ 0.        ]]
[[ 0.         0.        -0.0086635  0.       ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-6.24500451e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.00632947 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.08166817e-17]
 [0.000000

[[0.       ]
 [0.0163052]
 [0.       ]
 [0.       ]]
[[0.         0.         0.         0.90208551]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.01438877]]
[[-0.81580177  0.          0.          0.        ]]
[[0.05485625]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.07636942 0.         0.         0.        ]]
[[-4.16333634e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.02114839 0.         0.         0.        ]]
[[-2.42861287e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.00585625]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.05455131]]
[[0.67683257 0.         0.         0.        ]]
[[0.03552891]
 [0.        ]
 [0.        ]
 [0.        ]]
[[-0.48767  0.       0.       0.     ]]
[[-5.20417043e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.50939557]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.01751805]]
[[0.         0.08482938 0.         0.  

 [0.00000000e+00]]
[[-0.00299471  0.          0.          0.        ]]
[[6.9388939e-18]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]
[[-0.04041812  0.          0.          0.        ]]
[[-3.46944695e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.02840196]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00450295]]
[[0.         0.         0.         0.00550471]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]]
[[ 0.          0.         -0.04510291  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00146669]
 [ 0.        ]]
[[0.         0.         0.19341625 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]
 [ 0.00000000e+00]]
[[ 0.         -0.15544748  0.          0.        ]]
[[ 0.        ]
 [-0.00234982]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.03569723  0.        ]]
[[0.        ]
 [0.        ]
 [0.00210288]
 [0.        ]]
[[-0.02035162  0.          0.        

 [0.       ]]
[[ 0.          0.         -0.07013613  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00016716]
 [ 0.        ]]
[[0.        0.        0.        0.0113236]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.85551028e-05]]
[[0.         0.         0.         0.00377797]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.         -0.02544123  0.          0.        ]]
[[0.00000000e+00]
 [9.87579585e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.01398545 0.         0.         0.        ]]
[[-8.37010764e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00445882 0.         0.         0.        ]]
[[-3.12250226e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[2.05678252e-08 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
[[-8.67361738e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.72031456e-14]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.83975014e-05]]
[[0.00000000e+00 2.306

[[0.         0.         0.         0.09102371]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00017122]]
[[ 0.          0.         -0.07219195  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00189288]
 [ 0.        ]]
[[ 0.         -0.02619325  0.          0.        ]]
[[0.        ]
 [0.00024221]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -0.00790458]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00090867]]
[[0.10680659 0.         0.         0.        ]]
[[0.000522]
 [0.      ]
 [0.      ]
 [0.      ]]
[[ 0.         -0.10167281  0.          0.        ]]
[[ 0.        ]
 [-0.00045475]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.12204889]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.47722051e-05]]
[[0.00414996 0.         0.         0.        ]]
[[0.00053152]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.01270622 0.         0.         0.        ]]
[[-7.63278329e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]

[[0.         0.04820689 0.         0.        ]]
[[ 0.        ]
 [-0.00026218]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.01361615 0.         0.        ]]
[[ 0.00000000e+00]
 [-2.08166817e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.04949156]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00029264]]
[[0.01024179 0.         0.         0.        ]]
[[-0.00013483]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-0.0434511  0.         0.         0.       ]]
[[-3.46944695e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.01203581  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00016599]
 [ 0.        ]]
[[0.05226407 0.         0.         0.        ]]
[[0.00014678]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -0.03778744  0.          0.        ]]
[[ 0.       ]
 [-0.0001103]
 [ 0.       ]
 [ 0.       ]]
[[0.02623423 0.         0.         0.        ]]
[[0.00013564]
 [0.        ]
 [0.        ]
 [0.      

[[ 0.          0.         -0.00463619  0.        ]]
[[0.        ]
 [0.        ]
 [0.00080419]
 [0.        ]]
[[0.         0.         0.         0.02045198]]
[[ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [-0.0005722]]
[[ 0.          0.          0.         -0.01745037]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]]
[[ 0.         -0.12661171  0.          0.        ]]
[[0.        ]
 [0.00047499]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         0.14445543]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00015792]]
[[0.         0.         0.         0.01890609]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.        0.        0.0024744 0.       ]]
[[0.        ]
 [0.        ]
 [0.00039429]
 [0.        ]]
[[0.0525154 0.        0.        0.       ]]
[[-0.00014012]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.24135804  0.        ]]
[[0.        ]
 [0.        ]
 [0.00048732]
 [0.        ]]
[[0.         0.         0.         0.07718833]]
[[ 

[[ 0.00000000e+00 -9.68923664e-06  0.00000000e+00  0.00000000e+00]]
[[ 0.        ]
 [-0.00154567]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.03404228  0.        ]]
[[0.        ]
 [0.        ]
 [0.00169704]
 [0.        ]]
[[ 0.          0.         -0.02048235  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.85722573e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.03107906 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.77555756e-17]
 [0.00000000e+00]]
[[0.00000000e+00 9.94969773e-06 0.00000000e+00 0.00000000e+00]]
[[ 0.        ]
 [-0.00088088]
 [ 0.        ]
 [ 0.        ]]
[[0.01716106 0.         0.         0.        ]]
[[-0.00091559]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.00489245]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00146064]]
[[ 0.          0.          0.         -0.03795048]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.77555756e-17]]
[[ 0.         -0.01360717  0.          0.       

[[0.         0.         0.02016312 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [4.16333634e-17]
 [0.00000000e+00]]
[[ 0.          0.         -0.09528856  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-6.24500451e-17]
 [ 0.00000000e+00]]
[[ 0.         0.        -0.0181603  0.       ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.08166817e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.04500064]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00195553]]
[[0.        0.        0.0435024 0.       ]]
[[ 0.       ]
 [ 0.       ]
 [-0.0023703]
 [ 0.       ]]
[[0.01268809 0.         0.         0.        ]]
[[0.00173465]
 [0.        ]
 [0.        ]
 [0.        ]]
[[-0.08775126  0.          0.          0.        ]]
[[-6.9388939e-18]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[ 0.          0.         -0.01951917  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00035104]
 [ 0.        ]]
[[-0.00371718  0.          0.          0.        ]]
[[0.00047902]
 [0.      

 [-0.00026304]]
[[0.         0.04723079 0.         0.        ]]
[[ 0.        ]
 [-0.00050158]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.03593912  0.          0.        ]]
[[0.00000000e+00]
 [1.73472348e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -0.06719154  0.        ]]
[[0.        ]
 [0.        ]
 [0.00038505]
 [0.        ]]
[[0.04355477 0.         0.         0.        ]]
[[0.00121582]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         0.00730223]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00061214]]
[[0.         0.06896108 0.         0.        ]]
[[ 0.        ]
 [-0.00068049]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.04838288]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00011649]]
[[ 0.          0.         -0.07986094  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00044357]
 [ 0.        ]]
[[0.         0.04313486 0.         0.        ]]
[[0.       ]
 [0.0014955]
 [0.       ]
 [0.     

 [0.00000000e+00]]
[[0.02961212 0.         0.         0.        ]]
[[2.01025976e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         0.         0.        -0.0309552]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00031592]]
[[-0.03881759  0.          0.          0.        ]]
[[0.0005387]
 [0.       ]
 [0.       ]
 [0.       ]]
[[0.02773816 0.         0.         0.        ]]
[[-2.42861287e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.         -0.03080562  0.          0.        ]]
[[0.        ]
 [0.00046611]
 [0.        ]
 [0.        ]]
[[0.         0.07299956 0.         0.        ]]
[[ 0.0000000e+00]
 [-7.2858386e-17]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[ 0.         -0.02168722  0.          0.        ]]
[[0.00000000e+00]
 [3.46944695e-18]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.00120808 0.         0.        ]]
[[0.00000000e+00]
 [4.51028104e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.02048727 0.         0.        

[[ 0.          0.         -0.01514044  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00087114]
 [ 0.        ]]
[[0.         0.         0.01739132 0.        ]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.00465916 0.         0.         0.        ]]
[[0.00060016]
 [0.        ]
 [0.        ]
 [0.        ]]
[[-0.02077479  0.          0.          0.        ]]
[[-3.46944695e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.01617778 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00023704]
 [ 0.        ]]
[[0.         0.         0.00433632 0.        ]]
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [-6.9388939e-18]
 [ 0.0000000e+00]]
[[0.         0.         0.         0.00116165]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00044735]]
[[ 0.          0.         -0.01018366  0.        ]]
[[0.        ]
 [0.        ]
 [0.00032287]
 [0.        ]]
[[0.0074483 0.        0.        0.       ]]
[[0.00011328]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         0.        -0.0223

[[-0.00132019  0.          0.          0.        ]]
[[-4.00509292e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.00572536  0.          0.          0.        ]]
[[-2.08166817e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.00158565  0.          0.          0.        ]]
[[-2.08166817e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.00730839]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00012844]]
[[ 0.          0.         -0.00113505  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00022936]
 [ 0.        ]]
[[-0.00030198  0.          0.          0.        ]]
[[1.35889825e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         0.        -0.0049751  0.       ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-6.43276333e-06]
 [ 0.00000000e+00]]
[[0.         0.00129809 0.         0.        ]]
[[0.00000000e+00]
 [3.18823508e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.       

[[0.         0.         0.00140488 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [8.30169902e-06]
 [0.00000000e+00]]
[[0.         0.         0.         0.00037643]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.38428947e-05]]
[[0.00000000e+00 2.23276899e-07 0.00000000e+00 0.00000000e+00]]
[[ 0.00000000e+00]
 [-4.50728332e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.00228686  0.          0.          0.        ]]
[[-1.66261637e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         -0.00063337]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.29894971e-05]]
[[0.00315072 0.         0.         0.        ]]
[[-4.61754388e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[4.34856515e-09 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
[[6.9388939e-18]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.00000000e+00 1.69664799e-05 0.00000000e+00 0.00000000e+00]]
[[ 0.00000000e+00]
 [-1.06538443e-05]
 [ 

 [0.        ]]
[[-0.11339254  0.          0.          0.        ]]
[[-0.00323946]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.03214665  0.        ]]
[[0.        ]
 [0.        ]
 [0.00567076]
 [0.        ]]
[[0.       0.       0.216946 0.      ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [4.85722573e-17]
 [0.00000000e+00]]
[[0.         0.         0.04100072 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [9.02056208e-17]
 [0.00000000e+00]]
[[ 0.         -0.02091299  0.          0.        ]]
[[ 0.       ]
 [-0.0033175]
 [ 0.       ]
 [ 0.       ]]
[[ 0.        -0.1830395  0.         0.       ]]
[[0.00000000e+00]
 [1.38777878e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.         0.00258342]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00434345]]
[[0.00047266 0.         0.         0.        ]]
[[-0.00436295]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.00014108 0.        ]]
[[0.        ]
 [0.        ]
 [0.00616

[[0.04842966 0.         0.         0.        ]]
[[0.00027754]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -0.10022177  0.          0.        ]]
[[ 0.        ]
 [-0.00115722]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.05483748  0.          0.        ]]
[[ 0.0000000e+00]
 [-6.9388939e-17]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[0.        0.        0.        0.0870053]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00410032]]
[[-0.05933511  0.          0.          0.        ]]
[[-0.00100441]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.07723959 0.        ]]
[[0.        ]
 [0.        ]
 [0.00010804]
 [0.        ]]
[[0.         0.         0.         0.02072125]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00086807]]
[[-0.11020246  0.          0.          0.        ]]
[[-0.00179601]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.05923718  0.          0.        ]]
[[ 0.        ]
 [-0.00095513]
 [ 0.        ]
 [ 0.        ]]
[[0.155

[[ 0.         -0.05759986  0.          0.        ]]
[[0.00000000e+00]
 [1.38777878e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.         0.28575112]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00508258]]
[[0.         0.         0.         0.03647958]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.          0.          0.         -0.31205398]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.38777878e-17]]
[[ 0.          0.         -0.06082946  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00298611]
 [ 0.        ]]
[[0.         0.         0.         0.01724206]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00261898]]
[[ 0.          0.          0.         -0.02494852]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[-0.00516904  0.          0.          0.        ]]
[[0.00056916]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.3369407 0.        0.        0.       ]]
[[-2.77555756e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.23455412  0.          0.          0.  

 [ 0.        ]]
[[0.         0.85525993 0.         0.        ]]
[[0.00000000e+00]
 [2.94902991e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.          0.         -0.60647487]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00160319]]
[[0.         0.64238836 0.         0.        ]]
[[0.        ]
 [0.00552112]
 [0.        ]
 [0.        ]]
[[ 0.         -0.67183186  0.          0.        ]]
[[0.00000000e+00]
 [3.98986399e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -0.20703371  0.        ]]
[[0.        ]
 [0.        ]
 [0.00506035]
 [0.        ]]
[[0.         1.03468528 0.         0.        ]]
[[ 0.        ]
 [-0.00508637]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.63065661  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00579363]
 [ 0.        ]]
[[0.77183549 0.         0.         0.        ]]
[[0.00191615]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -0.28418811  0.          0.        ]]
[[0.        ]
 [0.01287688]
 [0.

[[ 0.         -0.44567864  0.          0.        ]]
[[0.        ]
 [0.01232358]
 [0.        ]
 [0.        ]]
[[0.         0.49904116 0.         0.        ]]
[[0.00000000e+00]
 [2.94902991e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.14934752 0.         0.        ]]
[[ 0.00000000e+00]
 [-1.56125113e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.04468863 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.01054878]
 [ 0.        ]]
[[ 0.          0.          0.         -0.18943071]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00120465]]
[[ 0.          0.          0.         -0.03689731]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.          0.          0.         -0.00718735]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.55111512e-17]]
[[0.         0.         0.         0.24558744]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]]
[[-0.1991463  0.         0.         0.       ]]
[[0.00194931]
 [0.        ]
 [0.        ]
 [0.  

 [ 0.00000000e+00]]
[[0.         1.77523594 0.         0.        ]]
[[ 0.00000000e+00]
 [-8.67361738e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         2.72864818 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00915471]
 [ 0.        ]]
[[ 0.          0.          0.         -1.47125446]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.03514382]]
[[ 0.         -2.26376406  0.          0.        ]]
[[ 0.        ]
 [-0.03216254]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         2.79964909]]
[[0.       ]
 [0.       ]
 [0.       ]
 [0.0178661]]
[[ 0.          0.         -2.91287745  0.        ]]
[[0.        ]
 [0.        ]
 [0.01969998]
 [0.        ]]
[[0.         0.         0.92484439 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [5.55111512e-17]
 [0.00000000e+00]]
[[ 0.          0.          0.         -1.45181497]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.05588661]]
[[ 0.          0.         -0.29984925  0.        ]]
[[ 0.       ]
 [ 0.       ]


[[0.         0.         0.39945154 0.        ]]
[[0.        ]
 [0.        ]
 [0.14876589]
 [0.        ]]
[[0.         0.         0.         0.01076621]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.05115568]]
[[-6.81778886  0.          0.          0.        ]]
[[0.03952971]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         1.73384022 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.18380171]
 [ 0.        ]]
[[0.         0.         0.         0.83393578]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.11728514]]
[[2.50072661 0.         0.         0.        ]]
[[-0.04978527]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-4.45731273  0.          0.          0.        ]]
[[3.46944695e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         3.91726133 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.03879221]
 [ 0.        ]]
[[0.         0.         0.00036528 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.04083409e-17]
 [ 0.00000000e+

[[ 0.         -0.01741273  0.          0.        ]]
[[0.00000000e+00]
 [2.58844662e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.07416776 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.34496789e-05]
 [0.00000000e+00]]
[[0.         0.         0.         0.11798899]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.83856317e-05]]
[[-0.07363063  0.          0.          0.        ]]
[[-1.71952998e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.05267327]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.05994123e-05]]
[[ 0.         -0.15138269  0.          0.        ]]
[[0.00000000e+00]
 [2.06874036e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.10626342 0.        ]]
[[0.00000e+00]
 [0.00000e+00]
 [6.22616e-06]
 [0.00000e+00]]
[[ 0.         -0.01422834  0.          0.        ]]
[[ 0.00000000e+00]
 [-2.10851041e-06]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.0

[[0.         0.         0.04044403 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.27474668e-24]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.32771992  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.30872245e-24]
 [ 0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.78775125e-17]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-8.40685225e-09]]
[[0.25038274 0.         0.         0.        ]]
[[1.7404813e-08]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.04304767 0.         0.         0.        ]]
[[-4.96308368e-24]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.04304767  0.          0.          0.        ]]
[[7.44462551e-24]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.00000000e+00 2.75347858e-17 0.00000000e+00 0.00000000e+00]]
[[0.0000000e+00]
 [3.7317911e-08]
 [0.0000000e+00]
 [0.0000000e+00]]
[[-0.00614593  0.          0.          0.        ]]
[[-2.62533296e-08]
 [ 0.00000000e+00]
 [ 0.000000

[[ 0.          0.          0.         -0.03014283]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.10026327e-26]]
[[-2.63403968e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[4.0670025e-11]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.         0.         0.         0.07752536]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.49815624e-11]]
[[ 0.         -0.07752536  0.          0.        ]]
[[0.00000000e+00]
 [9.72386401e-11]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         -0.02310626  0.          0.        ]]
[[0.00000000e+00]
 [1.45402842e-26]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.         0.05431806]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-6.98542265e-11]]
[[-0.06120482  0.          0.          0.        ]]
[[-2.96283527e-11]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.         -0.01742062  0.          0.        ]]
[[0.0000000e+00]
 [6.7016563e-11]
 [0.0000000e+00]
 [

[[ 0.         -0.15536607  0.          0.        ]]
[[0.00000000e+00]
 [5.83480965e-14]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.        -0.2490562  0.         0.       ]]
[[ 0.00000000e+00]
 [-7.88860905e-31]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.04520273e-16]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-8.19444812e-14]]
[[0.         0.00343902 0.         0.        ]]
[[0.0000000e+00]
 [4.8055381e-14]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.12610502 0.         0.         0.        ]]
[[-5.01833766e-14]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.09098574  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.02950643e-14]
 [0.00000000e+00]]
[[ 0.0000000e+00 -9.8265537e-17  0.0000000e+00  0.0000000e+00]]
[[0.00000000e+00]
 [3.60537617e-14]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-1.49988102e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[-2.81051797e-14]
 [ 0.00000000e

[[-0.23852776  0.          0.          0.        ]]
[[1.38505689e-19]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         0.        -1.2160126  0.       ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.44510188e-20]
 [ 0.00000000e+00]]
[[1.77304244 0.         0.         0.        ]]
[[2.33169978e-19]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.44845685  0.          0.          0.        ]]
[[-3.97223051e-34]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -1.87355262  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [7.08273882e-20]
 [0.00000000e+00]]
[[1.81763271 0.         0.         0.        ]]
[[2.80492482e-19]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -1.77163407  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-7.95856925e-20]
 [ 0.00000000e+00]]
[[0.         0.         1.23344973 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [3.61111865e-34]
 [0.00000000e+00]]
[[0.

[[ 0.         0.         0.        -0.3389924]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.93375707e-37]]
[[0.94138343 0.         0.         0.        ]]
[[5.67248388e-22]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.77585668  0.          0.          0.        ]]
[[1.88079096e-37]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.172454  0.        0.        0.      ]]
[[-1.41059322e-37]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.06070584 0.        ]]
[[0.0000000e+00]
 [0.0000000e+00]
 [7.6016519e-22]
 [0.0000000e+00]]
[[0.         0.         0.01634254 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.29304379e-37]
 [0.00000000e+00]]
[[0.         0.         0.89008543 0.        ]]
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [-4.7019774e-38]
 [ 0.0000000e+00]]
[[ 0.         -0.77313705  0.          0.        ]]
[[ 0.00000000e+00]
 [-1.13886328e-21]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.10873053  0.       

[[ 0.          0.         -0.85342046  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [7.26056021e-28]
 [0.00000000e+00]]
[[ 0.          0.          0.         -2.52051754]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.77535207]]
[[0.        0.0025346 0.        0.       ]]
[[ 0.        ]
 [-0.08054231]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.60088311]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.05403168]]
[[0.         0.         0.60062965 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.29107031]
 [ 0.        ]]
[[ 0.        -0.5630418  0.         0.       ]]
[[0.        ]
 [0.06971427]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -0.00197259]]
[[0.       ]
 [0.       ]
 [0.       ]
 [0.1514846]]
[[0.         0.         0.00278353 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.10637713]
 [ 0.        ]]
[[0.         0.00153673 0.         0.        ]]
[[ 0.        ]
 [-0.04819699]
 [ 0.        ]
 [ 0.        ]]
[[0.0008148

 [0.        ]]
[[-4.50455636  0.          0.          0.        ]]
[[0.00503916]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         2.71000212 0.        ]]
[[0.        ]
 [0.        ]
 [0.06673985]
 [0.        ]]
[[ 0.          0.          0.         -3.95288436]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.06791679]]
[[0.         0.         3.94483111 0.        ]]
[[0.        ]
 [0.        ]
 [0.05234735]
 [0.        ]]
[[0.         0.         0.77416002 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.51534904e-17]
 [0.00000000e+00]]
[[ 0.          0.         -5.48742927  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [4.07660017e-17]
 [0.00000000e+00]]
[[0.         0.         4.55178905 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.21430643e-17]
 [ 0.00000000e+00]]
[[0.         2.31721594 0.         0.        ]]
[[0.        ]
 [0.16597964]
 [0.        ]
 [0.        ]]
[[0.         0.         2.48520574 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-

[[-1.35259554  0.          0.          0.        ]]
[[4.85722573e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -0.39409879  0.        ]]
[[ 0.       ]
 [ 0.       ]
 [-0.0801323]
 [ 0.       ]]
[[ 0.          0.         -4.61402335  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-6.24500451e-17]
 [ 0.00000000e+00]]
[[0.         2.56136766 0.         0.        ]]
[[ 0.       ]
 [-0.0925334]
 [ 0.       ]
 [ 0.       ]]
[[2.50556235 0.         0.         0.        ]]
[[-0.00343044]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-0.33849712  0.          0.          0.        ]]
[[8.67361738e-18]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.         -0.86208344  0.          0.        ]]
[[0.        ]
 [0.05459346]
 [0.        ]
 [0.        ]]
[[-4.6108584  0.         0.         0.       ]]
[[0.02749998]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         3.77602368 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.0

 [0.        ]]
[[1.98555346 0.         0.         0.        ]]
[[-2.60208521e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.58477022 0.         0.         0.        ]]
[[6.9388939e-18]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.         0.         0.         0.17241256]]
[[ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [-0.0119931]]
[[-8.29083152  0.          0.          0.        ]]
[[-0.00724596]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         4.86073958 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.04320735]
 [ 0.        ]]
[[-0.94087407  0.          0.          0.        ]]
[[-0.03215765]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         1.68595596]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.17446373]]
[[ 0.        -3.9497608  0.         0.       ]]
[[ 0.        ]
 [-0.04203346]
 [ 0.        ]
 [ 0.        ]]
[[4.15716824 0.         0.         0.        ]]
[[-0.0169965]
 [ 0.       ]
 [ 0.    

[[0.        ]
 [0.        ]
 [0.        ]
 [0.01308513]]
[[ 0.         -0.93708941  0.          0.        ]]
[[0.        ]
 [0.01471675]
 [0.        ]
 [0.        ]]
[[0.         5.15251439 0.         0.        ]]
[[0.00000000e+00]
 [7.76288755e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[  0.         -28.14799751   0.           0.        ]]
[[ 0.00000000e+00]
 [-1.11889664e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         28.08925784]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.01521141]]
[[  0.         -26.78516915   0.           0.        ]]
[[0.        ]
 [0.01115722]
 [0.        ]
 [0.        ]]
[[  0.         -17.66869965   0.           0.        ]]
[[0.00000000e+00]
 [7.09068221e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.        -5.2647338  0.         0.       ]]
[[0.00000000e+00]
 [7.71951947e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -1.56872951  0.        ]]
[[0.        ]
 [0.        ]
 [0.02379591]
 [0.        ]]

 [0.        ]]
[[  0.         -11.93004937   0.           0.        ]]
[[0.00000000e+00]
 [2.67797937e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[  0.         -37.67556448   0.           0.        ]]
[[ 0.00000000e+00]
 [-2.03830008e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.         22.13931342  0.          0.        ]]
[[ 0.00000000e+00]
 [-7.69783542e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[  0.         -26.77456292   0.           0.        ]]
[[0.00000000e+00]
 [2.30935063e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.          0.         92.79217677]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00213744]]
[[ 0.         12.32005578  0.          0.        ]]
[[0.        ]
 [0.00129995]
 [0.        ]
 [0.        ]]
[[  0.         -55.24864401   0.           0.        ]]
[[ 0.00000000e+00]
 [-5.14996032e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[  0.         -15.36983165   0.           0.        ]]
[[ 0.00000000e+00]
 [-1.62630326e-19]
 [ 0.00000000e+00]
 

[[ 0.          0.         -4.70286376  0.        ]]
[[ 0.       ]
 [ 0.       ]
 [-0.0900493]
 [ 0.       ]]
[[11.85137889  0.          0.          0.        ]]
[[0.60558923]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -8.85001802]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.20692255]]
[[0.         0.         1.60819949 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.03161225]
 [ 0.        ]]
[[ 0.         -3.05977527  0.          0.        ]]
[[ 0.        ]
 [-0.05714341]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         2.58146858]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.05947614]]
[[-2.96919254  0.          0.          0.        ]]
[[0.13111288]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         12.15984847  0.          0.        ]]
[[0.        ]
 [0.03277905]
 [0.        ]
 [0.        ]]
[[ 0.        -8.3964896  0.         0.       ]]
[[0.00000000e+00]
 [2.35922393e-16]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 

 [0.        ]]
[[0.         0.         0.04324156 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00111115]
 [ 0.        ]]
[[ 0.          0.         -0.15414522  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.38777878e-17]
 [ 0.00000000e+00]]
[[0.         0.12338712 0.         0.        ]]
[[0.        ]
 [0.00011642]
 [0.        ]
 [0.        ]]
[[-0.08978378  0.          0.          0.        ]]
[[5.47042052e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.12734678 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-9.69221475e-05]
 [ 0.00000000e+00]]
[[0.        0.0359733 0.        0.       ]]
[[ 0.00000000e+00]
 [-3.22884474e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.17751788  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00021445]
 [ 0.        ]]
[[0.         0.         0.11101097 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [9.71445147e-17]
 [0.00000000e+00]]
[[0.         0.         0.         0.

[[-0.00025558]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.02133187  0.        ]]
[[0.        ]
 [0.        ]
 [0.00031798]
 [0.        ]]
[[0.         0.         0.         0.09029484]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00291164e-05]]
[[0.         0.         0.03234192 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00022835]
 [ 0.        ]]
[[0.         0.00652387 0.         0.        ]]
[[ 0.00000000e+00]
 [-2.42097924e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.11053902  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.45634011e-05]
 [ 0.00000000e+00]]
[[0.05111458 0.         0.         0.        ]]
[[-0.00030187]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.05151949  0.          0.        ]]
[[ 0.00000000e+00]
 [-1.02009472e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.0000000e+00 4.1910464e-05 0.0000000e+00 0.0000000e+00]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[-0.01572299  0.      

 [8.32667268e-17]]
[[0.         0.         0.01003578 0.        ]]
[[0.0000000e+00]
 [0.0000000e+00]
 [7.4450696e-05]
 [0.0000000e+00]]
[[0.02850361 0.         0.         0.        ]]
[[1.35484975e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.04288819  0.          0.          0.        ]]
[[-1.42247325e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.01323126]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.44320226e-05]]
[[ 0.          0.         -0.01056633  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.86726997e-05]
 [0.00000000e+00]]
[[ 0.        -0.0065337  0.         0.       ]]
[[0.        ]
 [0.00021459]
 [0.        ]
 [0.        ]]
[[0.         0.01662283 0.         0.        ]]
[[0.00000000e+00]
 [1.73472348e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.02601308 0.         0.        ]]
[[ 0.00000000e+00]
 [-8.67361738e-18]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.        

[[ 0.00000000e+00  0.00000000e+00 -4.46247781e-06  0.00000000e+00]]
[[0.00000000e+00]
 [0.00000000e+00]
 [7.77089451e-05]
 [0.00000000e+00]]
[[0.         0.         0.         0.06189547]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.04714827e-05]]
[[0.        0.0077518 0.        0.       ]]
[[0.        ]
 [0.00010736]
 [0.        ]
 [0.        ]]
[[-1.10305034e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[-7.0913206e-05]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[ 0.          0.          0.         -0.03839234]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.88648828e-05]]
[[0.         0.03358437 0.         0.        ]]
[[ 0.00000000e+00]
 [-2.50919461e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.04750561  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.06846304e-05]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.00725599  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.16333634e-17]


[[0.         0.         0.07354846 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [5.55111512e-17]
 [0.00000000e+00]]
[[0.         0.01483179 0.         0.        ]]
[[ 0.00000000e+00]
 [-8.26445326e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00000000e+00 1.48252834e-06 0.00000000e+00 0.00000000e+00]]
[[ 0.00000000e+00]
 [-2.25514052e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.05280595  0.          0.          0.        ]]
[[-5.96713265e-06]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         -0.01514946]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00033246]]
[[-0.0285548  0.         0.         0.       ]]
[[-8.67054061e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.0293104 0.        0.        0.       ]]
[[-3.81639165e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[-0.02910793  0.          0.          0.        ]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.        0.        0.0202114 0.       ]]
[[ 0.000

[[-0.00022151]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.01455272]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00013115]]
[[ 0.00000000e+00  0.00000000e+00 -3.86324966e-06  0.00000000e+00]]
[[ 0.        ]
 [ 0.        ]
 [-0.00012253]
 [ 0.        ]]
[[ 0.          0.         -0.04657331  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]
 [ 0.00000000e+00]]
[[-0.01316851  0.          0.          0.        ]]
[[6.06326732e-06]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.         0.00918075]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-9.90183685e-06]]
[[0.         0.         0.         0.00171255]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]]
[[0.         0.00031945 0.         0.        ]]
[[0.00000000e+00]
 [1.85482606e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.05032821 0.         0.        ]]
[[ 0.00000000e+00]
 [-8.6736

[[0.         0.00809621 0.         0.        ]]
[[0.        ]
 [0.00012526]
 [0.        ]
 [0.        ]]
[[-0.07026274  0.          0.          0.        ]]
[[-0.00013753]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.02873533]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.13390722e-05]]
[[0.        0.        0.0085674 0.       ]]
[[0.        ]
 [0.        ]
 [0.00024473]
 [0.        ]]
[[-0.01393007  0.          0.          0.        ]]
[[-6.02630928e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.01240147 0.         0.        ]]
[[0.00000000e+00]
 [8.71151015e-05]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.07149055 0.         0.         0.        ]]
[[-2.05588375e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         -0.10106867]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00028037]]
[[0.         0.         0.05382814 0.        ]]
[[ 0.00000000e+00]
 

[[ 0.         -7.66430673  0.          0.        ]]
[[0.        ]
 [0.03132664]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         18.73601678]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.01818873]]
[[0.         0.01203049 0.         0.        ]]
[[0.       ]
 [0.0132614]
 [0.       ]
 [0.       ]]
[[-17.29320295   0.           0.           0.        ]]
[[0.04250665]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         9.95016381 0.        ]]
[[0.       ]
 [0.       ]
 [0.0579151]
 [0.       ]]
[[-7.13876308  0.          0.          0.        ]]
[[-0.051109]
 [ 0.      ]
 [ 0.      ]
 [ 0.      ]]
[[ 0.         -3.84418341  0.          0.        ]]
[[ 0.        ]
 [-0.06360534]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         11.40013847]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.01237942]]
[[ 0.        -6.4109144  0.         0.       ]]
[[ 0.        ]
 [-0.03435904]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         6.0

[[ 0.         -6.07542271  0.          0.        ]]
[[ 0.        ]
 [-0.08652313]
 [ 0.        ]
 [ 0.        ]]
[[0.         6.03783865 0.         0.        ]]
[[ 0.00000000e+00]
 [-1.38777878e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         3.84891947]]
[[ 0.      ]
 [ 0.      ]
 [ 0.      ]
 [-0.041569]]
[[0.         0.         0.01453529 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.06249041]
 [ 0.        ]]
[[ 0.          0.          0.         -9.18738171]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.06146543]]
[[0.        0.        0.        4.4492904]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.46944695e-18]]
[[0.         0.         0.90124897 0.        ]]
[[0.        ]
 [0.        ]
 [0.00891721]
 [0.        ]]
[[0.         0.         4.08752853 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.60208521e-18]
 [0.00000000e+00]]
[[0.        0.        1.1921522 0.       ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.38344197e-16

[[0.         0.45884661 0.         0.        ]]
[[ 0.00000000e+00]
 [-7.63278329e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.58782874  0.        ]]
[[0.        ]
 [0.        ]
 [0.00679855]
 [0.        ]]
[[0.55622075 0.         0.         0.        ]]
[[-0.00386233]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.162571 0.       0.       0.      ]]
[[-3.38271078e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.52610237  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00273365]
 [ 0.        ]]
[[ 0.0000000e+00  0.0000000e+00 -2.3315491e-06  0.0000000e+00]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.46944695e-18]
 [ 0.00000000e+00]]
[[ 0.00000000e+00 -2.11431902e-12  0.00000000e+00  0.00000000e+00]]
[[ 0.      ]
 [-0.006828]
 [ 0.      ]
 [ 0.      ]]
[[ 0.0000000e+00 -6.4026969e-05  0.0000000e+00  0.0000000e+00]]
[[0.00000000e+00]
 [1.04083409e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.40

[[0.40463682 0.         0.         0.        ]]
[[2.34187669e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[-0.00998283  0.          0.          0.        ]]
[[-2.60208521e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.00999039]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00044294]]
[[ 0.         -0.01101093  0.          0.        ]]
[[0.        ]
 [0.00066992]
 [0.        ]
 [0.        ]]
[[0.         0.00965693 0.         0.        ]]
[[ 0.00000000e+00]
 [-4.16333634e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.00965831  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.00084882e-05]
 [ 0.00000000e+00]]
[[-0.00187152  0.          0.          0.        ]]
[[-0.00019061]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.29857141  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.46136038e-05]
 [0.00000000e+00]]
[[0.         0.         0.         0.060

[[ 0.          0.         -0.13995062  0.        ]]
[[0.0000000e+00]
 [0.0000000e+00]
 [5.2909066e-17]
 [0.0000000e+00]]
[[ 0.         -0.02714578  0.          0.        ]]
[[0.        ]
 [0.01237053]
 [0.        ]
 [0.        ]]
[[0.         0.         0.87050529 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00400379]
 [ 0.        ]]
[[-0.70175455  0.          0.          0.        ]]
[[-0.01218671]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         -0.15094267  0.          0.        ]]
[[0.        ]
 [0.00634603]
 [0.        ]
 [0.        ]]
[[0.22524918 0.         0.         0.        ]]
[[-0.00439823]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.69614759 0.         0.        ]]
[[0.        ]
 [0.00168134]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -0.48437408]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.04338039]]
[[-0.4427109  0.         0.         0.       ]]
[[-0.00632103]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-0.09

[[-0.6501601  0.         0.         0.       ]]
[[0.09505709]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.         -2.09227367  0.          0.        ]]
[[0.        ]
 [0.02387892]
 [0.        ]
 [0.        ]]
[[0.         0.         1.45138372 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.02738339]
 [ 0.        ]]
[[0.         0.         0.41257564 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.94902991e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.11678529 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.72458747e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.         3.95527923]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00182047]]
[[0.         0.         0.45721451 0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.10404582]
 [ 0.        ]]
[[ 0.          0.         -3.44638277  0.        ]]
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [-6.9388939e-17]
 [ 0.0000000e+00]]
[[ 0.          0.         -0.97554941  0.        ]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.   

[[0.         4.94038797 0.         0.        ]]
[[ 0.        ]
 [-0.05965887]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.00014173 0.         0.        ]]
[[ 0.00000000e+00]
 [-2.77555756e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00000000e+00 0.00000000e+00 5.15774503e-09 0.00000000e+00]]
[[ 0.        ]
 [ 0.        ]
 [-0.08560953]
 [ 0.        ]]
[[0.         0.         0.82618217 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.21430643e-17]
 [0.00000000e+00]]
[[0.         0.         0.         0.24274103]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.04803762]]
[[ 0.          0.          0.         -0.87641404]]
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [-6.9388939e-18]]
[[0.         0.         0.         0.98715372]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.73472348e-18]]
[[-4.70822073  0.          0.          0.        ]]
[[-0.00479742]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[4.90475228 0.         0.         0.        ]]
[[8.

[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.08166817e-17]]
[[ 0.         -0.00492601  0.          0.        ]]
[[ 0.        ]
 [-0.00323545]
 [ 0.        ]
 [ 0.        ]]
[[0.08072681 0.         0.         0.        ]]
[[0.0077097]
 [0.       ]
 [0.       ]
 [0.       ]]
[[ 0.        -0.0521496  0.         0.       ]]
[[ 0.      ]
 [-0.005336]
 [ 0.      ]
 [ 0.      ]]
[[0.         0.05944656 0.         0.        ]]
[[ 0.0000000e+00]
 [-3.2959746e-17]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[ 0.         0.         0.        -0.0851836]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00222369]]
[[0.         0.         0.08566332 0.        ]]
[[0.        ]
 [0.        ]
 [0.00127108]
 [0.        ]]
[[ 0.00000000e+00  0.00000000e+00 -1.55727234e-05  0.00000000e+00]]
[[0.00000000e+00]
 [0.00000000e+00]
 [9.97465999e-18]
 [0.00000000e+00]]
[[ 0.          0.          0.         -0.05343404]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00152426]]
[[0.         0.01318643 0.     

[[0.         0.         0.28014369 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.12503626e-17]
 [ 0.00000000e+00]]
[[0.         0.03710827 0.         0.        ]]
[[0.       ]
 [0.0003382]
 [0.       ]
 [0.       ]]
[[0.         0.         0.         0.20949721]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00034448]]
[[ 0.          0.         -0.48686517  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00020167]
 [ 0.        ]]
[[0.         0.52555694 0.         0.        ]]
[[0.        ]
 [0.00153784]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         0.14360245]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00150239]]
[[ 0.          0.          0.         -0.31742695]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.08166817e-17]]
[[ 0.         -0.36293816  0.          0.        ]]
[[ 0.        ]
 [-0.00155774]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.11022723  0.        ]]
[[0.        ]
 [0.        ]
 [0.00061635]
 [0.        ]]

[[0.         0.         0.03667497 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.68882139e-17]
 [0.00000000e+00]]
[[-0.15859555  0.          0.          0.        ]]
[[0.00582124]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.57294083 0.         0.         0.        ]]
[[-2.77555756e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.45339697  0.        ]]
[[0.        ]
 [0.        ]
 [0.00078192]
 [0.        ]]
[[ 0.          0.         -0.12839678  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.30104261e-18]
 [ 0.00000000e+00]]
[[0.         0.         0.         0.01575825]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.75265813e-05]]
[[0.         0.72178092 0.         0.        ]]
[[ 0.       ]
 [-0.0007169]
 [ 0.       ]
 [ 0.       ]]
[[ 0.         -0.55553994  0.          0.        ]]
[[0.00000000e+00]
 [2.42861287e-17]
 [0.00000000e+00]
 [0.00000000e+00]]
[[ 0.          0.         -0.16806202  0.        ]]


[[ 0.          0.         -0.09723526  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.73472348e-17]
 [ 0.00000000e+00]]
[[ 0.          0.          0.         -0.02700332]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00132997]]
[[0.         1.51757168 0.         0.        ]]
[[0.        ]
 [0.01174802]
 [0.        ]
 [0.        ]]
[[0.        0.0001244 0.        0.       ]]
[[ 0.00000000e+00]
 [-2.08166817e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[1.03263857 0.         0.         0.        ]]
[[-0.00404961]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.73523524]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.02481318]]
[[ 0.          0.          0.         -0.32164421]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.12250226e-17]]
[[ 0.          0.         -1.17767351  0.        ]]
[[0.        ]
 [0.        ]
 [0.00574688]
 [0.        ]]
[[0.        0.        1.1655603 0.       ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00

 [0.        ]]
[[0.         0.00020823 0.         0.        ]]
[[ 0.0000000e+00]
 [-6.9388939e-17]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]
[[ 0.         -1.59338634  0.          0.        ]]
[[0.0000000e+00]
 [6.9388939e-18]
 [0.0000000e+00]
 [0.0000000e+00]]
[[0.         0.         1.32576237 0.        ]]
[[0.        ]
 [0.        ]
 [0.00229733]
 [0.        ]]
[[ 0.00000000e+00  0.00000000e+00 -1.57367935e-05  0.00000000e+00]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.12250226e-17]
 [ 0.00000000e+00]]
[[ 0.         -1.43896299  0.          0.        ]]
[[0.        ]
 [0.00100114]
 [0.        ]
 [0.        ]]
[[0.         0.         2.21879155 0.        ]]
[[0.        ]
 [0.        ]
 [0.00228856]
 [0.        ]]
[[0.        0.6283882 0.        0.       ]]
[[0.        ]
 [0.00554012]
 [0.        ]
 [0.        ]]
[[0.        0.        0.1894489 0.       ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00078927]
 [ 0.        ]]
[[0.         0.         0.05369132 0.        ]]
[[0.00000000e+00]
 [0.000

[[ 0.         0.        -0.2472473  0.       ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00431562]
 [ 0.        ]]
[[ 0.          0.         -0.04681378  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-8.67361738e-19]
 [ 0.00000000e+00]]
[[ 0.          0.         -3.49637801  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [3.90312782e-17]
 [0.00000000e+00]]
[[0.         0.         3.10635758 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.73472348e-18]
 [0.00000000e+00]]
[[0.88022867 0.         0.         0.        ]]
[[-0.0025751]
 [ 0.       ]
 [ 0.       ]
 [ 0.       ]]
[[ 0.         -3.75128812  0.          0.        ]]
[[0.        ]
 [0.01527928]
 [0.        ]
 [0.        ]]
[[ 0.          0.         -1.02350836  0.        ]]
[[0.        ]
 [0.        ]
 [0.00483603]
 [0.        ]]
[[3.60695786 0.         0.         0.        ]]
[[0.05274035]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.          0.         -2.64227933  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.0

[[0.01575043]
 [0.        ]
 [0.        ]
 [0.        ]]
[[-0.87900673  0.          0.          0.        ]]
[[3.46944695e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.82143968 0.         0.         0.        ]]
[[3.46944695e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.         0.44080965 0.        ]]
[[0.        ]
 [0.        ]
 [0.00111244]
 [0.        ]]
[[0.08422147 0.         0.         0.        ]]
[[-0.00605009]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.28167878  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00094882]
 [ 0.        ]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 6.79252641e-06]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00172358]]
[[-3.2400918e-05  0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[0.00237304]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         2.87138059]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.09459129]]
[[0.         0.        

[[0.         0.         0.20676388 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.77555756e-17]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.38047689  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.90819582e-17]
 [0.00000000e+00]]
[[0.         0.         0.34738941 0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-3.90312782e-17]
 [ 0.00000000e+00]]
[[0.         0.         0.06616797 0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.08166817e-17]
 [0.00000000e+00]]
[[-0.23983909  0.          0.          0.        ]]
[[-0.00103628]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.          0.         -0.16452109]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.00205176]]
[[0.         0.         0.34812371 0.        ]]
[[0.        ]
 [0.        ]
 [0.00076754]
 [0.        ]]
[[ 0.          0.         -0.27791076  0.        ]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.42861287e-17]
 [ 0.00000000e+00]]
[[ 0.          0.         -0.24135875  0.       

[[ 0.          0.          0.         -0.94712689]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.67361738e-18]]
[[0.46399062 0.         0.         0.        ]]
[[0.0124902]
 [0.       ]
 [0.       ]
 [0.       ]]
[[ 0.          0.         -0.65442449  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00053477]
 [ 0.        ]]
[[ 0.          0.          0.         -0.18263773]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00698745]]
[[-0.03674368  0.          0.          0.        ]]
[[0.00980049]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         1.19719186 0.        ]]
[[ 0.       ]
 [ 0.       ]
 [-0.0020219]
 [ 0.       ]]
[[ 0.         -0.86292083  0.          0.        ]]
[[ 0.        ]
 [-0.00490281]
 [ 0.        ]
 [ 0.        ]]
[[ 0.         0.        -0.2634004  0.       ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00242698]
 [ 0.        ]]
[[0.         0.56420624 0.         0.        ]]
[[ 0.        ]
 [-0.00410922]
 [ 0.        ]
 [ 0.        ]]
[[ 

 [0.        ]]
[[0.         2.31282744 0.         0.        ]]
[[ 0.       ]
 [-0.0100316]
 [ 0.       ]
 [ 0.       ]]
[[ 0.          0.         -1.71251696  0.        ]]
[[0.        ]
 [0.        ]
 [0.00306512]
 [0.        ]]
[[0.00000000e+00 0.00000000e+00 8.41461474e-06 0.00000000e+00]]
[[0.00000000e+00]
 [0.00000000e+00]
 [6.07153217e-18]
 [0.00000000e+00]]
[[1.38617687 0.         0.         0.        ]]
[[0.00949917]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         0.29231583 0.        ]]
[[ 0.       ]
 [ 0.       ]
 [-0.0004433]
 [ 0.       ]]
[[ 0.          0.          0.         -0.79928953]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00040275]]
[[0.         0.         0.76614099 0.        ]]
[[0.        ]
 [0.        ]
 [0.00043976]
 [0.        ]]
[[ 0.          0.          0.         -1.41978046]]
[[0.       ]
 [0.       ]
 [0.       ]
 [0.0003564]]
[[0.         0.         0.         0.87214563]]
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+

 [ 0.        ]]
[[ 0.          0.          0.         -2.68407206]]
[[0.      ]
 [0.      ]
 [0.      ]
 [0.006602]]
[[0.         1.79559871 0.         0.        ]]
[[0.        ]
 [0.06318902]
 [0.        ]
 [0.        ]]
[[0.         0.         1.98762682 0.        ]]
[[0.        ]
 [0.        ]
 [0.00565289]
 [0.        ]]
[[ 0.          0.         -2.18340764  0.        ]]
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [-1.6479873e-17]
 [ 0.0000000e+00]]
[[ 0.          0.         -1.59720764  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [2.68882139e-17]
 [0.00000000e+00]]
[[0.00000000e+00 0.00000000e+00 6.88623623e-07 0.00000000e+00]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.47451495e-17]
 [0.00000000e+00]]
[[0.87688286 0.         0.         0.        ]]
[[-0.02284067]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[0.         0.         0.         0.96109924]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.01308265]]
[[0.         0.19382225 0.         0.        ]]
[[0.        ]
 [0.01

[[ 0.          0.          0.         -0.18815424]]
[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.04083409e-17]]
[[ 0.          0.         -0.27969339  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00295224]
 [ 0.        ]]
[[ 0.          0.         -0.07817761  0.        ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [6.07153217e-18]
 [0.00000000e+00]]
[[ 0.         -0.02183742  0.          0.        ]]
[[0.        ]
 [0.01388813]
 [0.        ]
 [0.        ]]
[[ 0.          0.         -0.00701107  0.        ]]
[[0.        ]
 [0.        ]
 [0.00325655]
 [0.        ]]
[[0.         0.         0.         1.92078882]]
[[ 0.      ]
 [ 0.      ]
 [ 0.      ]
 [-0.007849]]
[[4.96784484e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
[[-0.00112598]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -1.41087272  0.        ]]
[[0.        ]
 [0.        ]
 [0.00330826]
 [0.        ]]
[[0.         0.         0.         2.82149131]]
[[ 0.00000000e+00]
 [ 0.00000000e+00

 [ 0.00000000e+00]]
[[-2.91118651  0.          0.          0.        ]]
[[0.04193544]
 [0.        ]
 [0.        ]
 [0.        ]]
[[ 0.          0.         -0.00115939  0.        ]]
[[0.        ]
 [0.        ]
 [0.00711494]
 [0.        ]]
[[0.         4.93705695 0.         0.        ]]
[[ 0.        ]
 [-0.04855011]
 [ 0.        ]
 [ 0.        ]]
[[ 0.          0.         -0.29911886  0.        ]]
[[ 0.        ]
 [ 0.        ]
 [-0.00010056]
 [ 0.        ]]
[[ 0.         -0.08535094  0.          0.        ]]
[[0.        ]
 [0.00037611]
 [0.        ]
 [0.        ]]
[[ 0.          0.          0.         -3.15416271]]
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.02532251]]
[[4.30189625 0.         0.         0.        ]]
[[0.06066044]
 [0.        ]
 [0.        ]
 [0.        ]]
[[1.15085347 0.         0.         0.        ]]
[[1.73472348e-17]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.         0.30878795 0.         0.        ]]
[[0.        ]
 [0.03117931]
 [0.        ]
 [

In [51]:
A, S, error = mf(data, k = 4, s = 1, niter = 10, siter = 1000, solver = 'bgs', errseq = True)
print(error)

[0.82372971 0.83849927 0.84501163 4.4763483  4.44162822 4.45065825
 1.01900878 1.02977303 1.21722607 1.66866681]


In [66]:
np.linalg.norm(np.eye(A.shape[0]) - np.matmul(np.linalg.pinv(np.matmul(A, S)), np.matmul(A, S)))

14.0

In [71]:
lfactor = np.random.rand(data.shape[0], 4)
rfactor = np.random.rand(4, data.shape[1])
np.linalg.norm(np.eye(lfactor.shape[0]) - np.matmul(np.linalg.pinv(np.matmul(lfactor, rfactor)), np.matmul(lfactor, rfactor)))

13.999999999999998

In [73]:
np.matmul(np.linalg.pinv(np.matmul(lfactor, rfactor)), np.matmul(lfactor, rfactor))

array([[ 0.01006647,  0.0069343 ,  0.0031056 , ...,  0.00640015,
         0.00751692,  0.00663376],
       [ 0.0069343 ,  0.00953661, -0.00300923, ...,  0.00889978,
         0.00768869,  0.00902666],
       [ 0.0031056 , -0.00300923,  0.01265437, ..., -0.00421445,
         0.00252048, -0.0030961 ],
       ...,
       [ 0.00640015,  0.00889978, -0.00421445, ...,  0.00925231,
         0.00790242,  0.01024711],
       [ 0.00751692,  0.00768869,  0.00252048, ...,  0.00790242,
         0.01126107,  0.01086032],
       [ 0.00663376,  0.00902666, -0.0030961 , ...,  0.01024711,
         0.01086032,  0.0132491 ]])

In [74]:
np.matmul(np.linalg.pinv(np.matmul(A, S)), np.matmul(A, S))

array([[ 2.49958565e-02,  2.47238183e-04,  2.01533692e-02, ...,
         2.49102207e-03, -1.04348010e-02, -2.36928778e-03],
       [ 2.47238183e-04,  8.58452844e-03,  2.90765035e-05, ...,
         1.15869212e-02,  8.35029591e-03,  1.43999321e-02],
       [ 2.01533692e-02,  2.90765035e-05,  1.91201325e-02, ...,
         5.69826621e-03, -5.45004205e-03, -3.74413236e-03],
       ...,
       [ 2.49102207e-03,  1.15869212e-02,  5.69826621e-03, ...,
         3.50074321e-02,  1.26086912e-02,  1.78745564e-02],
       [-1.04348010e-02,  8.35029591e-03, -5.45004205e-03, ...,
         1.26086912e-02,  1.63962059e-02,  1.33906717e-02],
       [-2.36928778e-03,  1.43999321e-02, -3.74413236e-03, ...,
         1.78745564e-02,  1.33906717e-02,  2.53458923e-02]])

In [79]:
k = 4
s = 1
lf = np.random.rand(data.shape[0], k)
rf = np.random.rand(k, data.shape[1])

approx = np.matmul(lf, rf)

# weighted sampling of row and column from data matrix
# specifying size returns an array rather than a scalar
row = np.random.choice(data.shape[0], size = 1, p = weightsample(approx, 1))
col = np.random.choice(data.shape[1], size = 1, p = weightsample(approx, 0))

if s == 1:
    gsrow = np.random.choice(rf.shape[0], size = s, p = weightsample(rf, 1))
    gscol = np.random.choice(lf.shape[1], size = s, p = weightsample(lf, 0))
else:
    resample = True
    while(resample):
        rowsum = 0
        colsum = 0
        gscol = np.random.choice(lf.shape[1], size = s, replace = False)
        gsrow = np.random.choice(rf.shape[0], size = s, replace = False)

        for samplerow in gsrow:
            rowsum = rowsum + sum(lf[samplerow, :])
        for samplecol in gscol:
            colsum = colsum + sum(rf[:, samplerow])
        if (rowsum > 0 and colsum > 0):
            resample = False

# compute BGS step
lf[row, :] = lf[row, :] + np.matmul((data[row, :] - np.matmul(lf[row, :], rf)), np.matmul(np.linalg.pinv(rf[gsrow, :]), np.eye(k)[:, gscol].T))
rf[:, col] = rf[:, col] + np.matmul(np.matmul(np.eye(k)[:, gscol], np.linalg.pinv(lf[:, gscol])), (data[:, col] - np.matmul(lf, rf[:, col])))


In [82]:
np.matmul((data[row, :] - np.matmul(lf[row, :], rf)), np.matmul(np.linalg.pinv(rf[gsrow, :]), np.eye(k)[:, gscol].T))

array([[ 0.        ,  0.        , -0.24859052,  0.        ]])